### ISSUE TITLE
Safari iOS memory error

### ISSUE THREAD

**Issue by dolbex** [hrynko/vue-pdf-embed#10]
Running into an error when displaying multiple pages on a 4MB PDF. 

```
Total canvas memory use exceeds the maximum limit (256 MB)" error in safari 12 and above
```

I've seen errors like this elsewhere that seem to be addressed: https://github.com/mozilla/pdf.js/issues/11297

I forked this repo and updated the pdf-dist package and that didn't seem to help. Maybe my implementation is incorrect? Anybody run into this?

**Comment by hrynko** [comment]
At first glance, this looks like a Safari limitation. However, I'll try to find out if it is possible to resolve this within the library later.

**Comment by hrynko** [comment]
Hi @dolbex,

In version `1.1.3`, a fix for [canvas utilization](https://pqina.nl/blog/total-canvas-memory-use-exceeds-the-maximum-limit/) was released. This can solve the single page view (when `page` prop is provided), but there may still be an issue with displaying the entire document. However, I will try to implement lazy loading (rendering) to solve this issue by the next minor version, as I see no other way so far.

**Comment by hoomb** [comment]
Hello @hrynko is there any workaround to fix this issue on multi page pdf documents?

**Comment by hrynko** [comment]
Hi @hoomb,

Please keep an eye on #161, I think this might be the solution
