### ISSUE TITLE
IDs not showing in DOM, it may be useful to make pagination

### ISSUE THREAD

**Issue by mmxhello** [hrynko/vue-pdf-embed#104]
Hello, I see that in your code there is an :id parameter in v-for, but it the page html there are no any IDs:
![image](https://user-images.githubusercontent.com/60787898/208239702-a1776504-1e10-4171-a109-c2d2fbab595a.png)

![image](https://user-images.githubusercontent.com/60787898/208239586-bf02a41d-7795-4435-a9d6-8b8254ec70cb.png)

I know that it is a vue feuture because :id is being added dynamically, but I think that it will be useful to dispolay these IDs in dom, for example, to make a page-navigation without breaking all document into separate pages (scrollIntoView, for example)

**Comment by mmxhello** [comment]
Finally, the solution for me was to add `:data-id="pageNum"` to div attributes in "vue-pdf-embed.vue" and select pages by it:
![image](https://user-images.githubusercontent.com/60787898/208243482-31733980-4413-4583-a727-d3dc5ff6f04f.png)

**Comment by hrynko** [comment]
Hi @mmxhello,

I'm not sure if we're on the same page, but the code below results in the DOM below:

```vue
<vue-pdf-embed id="foo" :source="pdfSource" />
```

<img width="293" alt="image" src="https://user-images.githubusercontent.com/28267443/210869328-c234a68e-ba06-4b43-bf39-314b66ae2fd4.png">

Thus, the `id` prop is set to the root component element, and each page element inherits it with the page number postfix. Please let me know if this is what you meant.
