### ISSUE TITLE
'scale' parameter causes view is not clear

### ISSUE THREAD

**Issue by jojo-d** [hrynko/vue-pdf-embed#106]

**Comment by brocard** [comment]
Yes i saw the same issue with scale parameter, the pdf turn blurred, i can share example if you want?

**Comment by hrynko** [comment]
Hi @brocard, yes please, it would be very helpful

**Comment by hrynko** [comment]
Well, I assume it may be a duplicate of https://github.com/hrynko/vue-pdf-embed/issues/93#issuecomment-1328030286. Please see the linked comment and feel free to reopen the issue if it isn't the case.
