### ISSUE TITLE
Xiaomi's MIUI 12.X App crashes after rendering more than 10 pages of PDF at a time.

### ISSUE THREAD

**Issue by ZmonGitHub** [hrynko/vue-pdf-embed#118]

**Comment by hrynko** [comment]
Hi @ZmonGitHub,

Thanks for opening the issue. Right now it is quite difficult to find out the cause from this description, but it can be useful in the future.

**Comment by hrynko** [comment]
After several memory usage optimzations and a switch to Vite, this may already be resolved in `v2.0.0`
