### ISSUE TITLE
not work.

### ISSUE THREAD

**Issue by chenweigh** [hrynko/vue-pdf-embed#122]
it is wrong.

`<vue-pdf-embed :source="source1" />`
`vue-pdf-embed: 1.1.5`

### Result
`<div class="vue-pdf-embed"></div>`

**Comment by hrynko** [comment]
Hi @chenweigh,

Could you provide more details on your environment and maybe prepare some demo?

**Comment by chenweigh** [comment]
My fault.
The installation did not work.
