### ISSUE TITLE
Internal links are not working

### ISSUE THREAD

**Issue by CG-root** [hrynko/vue-pdf-embed#126]
Hi
I'm trying to use the internal links feature.
When I try to press on the link, nothing happens.
When I look at the anchor, I see the following string:
http://localhost/page#[{"num":12,"gen":0},{"name":"XYZ"},68,724,0]

I'm not able to find any id with the value [{"num":12,"gen":0},{"name":"XYZ"},68,724,0]
What should be performed in order for this to work?

I also tried to use the project's example with a PDF file which includes internal links but it also does not seem to work.
[Example](https://jsfiddle.net/a8fhj1p9/1/)

Thanks!

**Comment by hrynko** [comment]
Hi @CG-root,

Internal links do not work our of the box, but can be handled by the proper event (`internal-link-clicked`, see [README](https://github.com/hrynko/vue-pdf-embed#events))
