### ISSUE TITLE
Failing test with vitest with error "Inline worker is not supported"

### ISSUE THREAD

**Issue by Chcap** [hrynko/vue-pdf-embed#127]
Hello,

When running a test with vitest on a component embeding `vue-pdf-embed`, the following error occurs: `Error: Inline worker is not supported`.

This error seems to be thrown by the [worker-loader](https://github.com/webpack-contrib/worker-loader/blob/22275e9cb0b67bc008ea2b008542303493eede18/src/runtime/inline.js#L46).

I tried using the stub mechanism used by [vue/test-utils](https://test-utils.vuejs.org/api/#global), but the error still occurs.

I found the fix used by @sbourouis for [jest](https://github.com/hrynko/vue-pdf-embed/issues/5) but did not found the same trick for vitest and vue/test-utils. 

I created the [vue-pdf-embed-bug-test-vitest](https://github.com/Chcap/vue-pdf-embed-bug-test-vitest) repo to help reproduce the issue.

Do you have any insight ?

Regards

**Comment by mattesalva93** [comment]
Hey,
don't know if you still need help on this, but had the same issue and i've found the fix only using vitest and vue/test-utils by adding this inside the 'describe' of the test file:

`  beforeEach(() => {
    vi.mock("vue-pdf-embed", () => ({
      default: { template: "<mock-vue-pdf-embed/>" }
    }));
  });
 `
 
Maybe this may be helpful for someone else,

Regards.

**Comment by Chcap** [comment]
Thanks a lot, it works well for me !

**Comment by markus-ebner** [comment]
I have used `@vitest/web-worker` for simulating a worker. I'm still not sure if it is a good solution, because I haven't written a complex test yet. But i'm currently working on more complex tests, so I'll keep you updated.
