### ISSUE TITLE
Large distribution package

### ISSUE THREAD

**Issue by coolhand79** [hrynko/vue-pdf-embed#128]
Thanks for the library, we're enjoying using it!

I do wonder if the build could be more optimized. At [1.6Mb](https://bundlephobia.com/package/vue-pdf-embed@1.1.2) it seems like it has an awfully large footprint. Pdfjs-dist comes in at only [264kb](https://bundlephobia.com/package/pdfjs-dist@3.4.120).

**Comment by hrynko** [comment]
Hi @coolhand79,

Most of this is the PDF worker, which is needed for the document loading. And since `vue-pdf-embed`  aims to be an all-in-one solution, the worker is included in the build.

As an option, adding more builds (without the worker) might be considered in the future.

**Comment by hrynko** [comment]
A build without a worker has been added in `v2.0.0`, and I will try to further reduce the build size in future releases. Thanks for pointing it out!
