### ISSUE TITLE
Width and Height inverted if PDF is rotated

### ISSUE THREAD

**Issue by sushi2all** [hrynko/vue-pdf-embed#129]
The component seems to take into account the rotation of pdf pages, but keeps rendering width and height without considering the page has been rotated.

E.g. if an original PDF has width 100 and height 200 (to keep things simple), and I rotate it 90 or 270 degrees, the height and width of the rendered content remain the same (width 100 and height 200), squeezing the rotated content into the forced dimensions. See example of a 2 page pdf where the first page has been rotated 90 degrees:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1043732/231394271-d911a58e-1175-4e38-8c8a-1a1e14f665ca.png">

**Comment by sushi2all** [comment]
Possibly this can be solved with the following change to the component `getPageDimensions` method?

```javascript
getPageDimensions(ratio) {
  let height, width
  if (this.height && !this.width) {
    height = this.height
    width = height / ratio
  } else {
    width = this.width || this.$el.clientWidth
    height = width * ratio
  }
  /* Height and width must be inverted if rotation 
   * is 90, 270, 450, etc., i.e. any degree like
   * ROTATION = 90 + 180x.
   * To figure out if dimensions must be inverted we can make 
   * the reverse formula anche check the following condition
   * (ROTATION - 90) % 180 == 0
   * 
   * Considering the rotation property can be a number or string
   * we must also convert it to number first
   */ 
  const invertDimensions = (Number(this.rotation) - 90) % 180 == 0
  return invertDimensions ? [height, width] : [width, height]
}
```

I'm not sure if this is enough to submit a pull request, I've never done it before 😅

**Comment by hrynko** [comment]
Hi @sushi2all,

I thought that this is handled by the following:

```js
if ((this.rotation / 90) % 2) {
  canvas.style.width = `${Math.floor(actualHeight)}px`
  canvas.style.height = `${Math.floor(actualWidth)}px`
} else {
  canvas.style.width = `${Math.floor(actualWidth)}px`
  canvas.style.height = `${Math.floor(actualHeight)}px`
}
```

But it seems like it could still be improved. Feel free to open a PR and let me know if I can help.

**Comment by hrynko** [comment]
Hi @sushi2all,

It's been a while since your issue was opened. Do you need help in opening a PR?

**Comment by sushi2all** [comment]
Pull request submitted: #136
