### ISSUE TITLE
The object is in an invalide state

### ISSUE THREAD

**Issue by nodous** [hrynko/vue-pdf-embed#133]
hello,
First of all, thank you for developing this component,
I encountered a problem while using it,
When iOS opens a PDF, some pages display blank pages,
Other browsers, Android phones are good
@rendering-failed will output the following log
`The object is in an invalid state`
Pages that cannot be displayed have several identical points

- The page is a long image
- The image is relatively large

![25581681650157_ pic](https://user-images.githubusercontent.com/32664888/232313504-b8856bc6-03c4-45e9-b278-eb0f001e4d7e.jpg)
![25571681650050_ pic](https://user-images.githubusercontent.com/32664888/232313508-8538e69d-1084-44c6-b9a2-91b213a00206.jpg)

**Comment by hrynko** [comment]
Hi @nodous,

The mentioned issue is raised by PDF.js, which is used internally. Thus, I suggest tracking the PDF.js repo issues (e.g. https://github.com/mozilla/pdf.js/issues/17190). Hopefully, it will explained there.

In the meantime, you can try installing `vue-pdf-embed@2`, the latest major version that has updated PDF.js, maybe it helps.
