### ISSUE TITLE
CMap font encoding

### ISSUE THREAD

**Issue by Fuzzy-Supernova** [hrynko/vue-pdf-embed#134]
Hello! I often get next warning messages when trying to view pdf files:
`Warning: loadFont - translateFont failed: "r: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.".`
`Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.`
Some text is also missing from the rendered pdf when this happens.
1) Could you please add support for CMap font encoding or give an example of how this could be done if it is already possible?
2) Also, is there a way to set `printResolution`, or increase image quality in any other way? Default render quality seems lacking if comparing with the browser built-in PDF viewer:(

Thanks in advance.

**Comment by hrynko** [comment]
Hi @Fuzzy-Supernova,

1. CMap can be provided with the `cMapUrl` prop. Please check the following issues: #80 #130
2. Do you mean resolution when rendering as a component or printing?

**Comment by Fuzzy-Supernova** [comment]
1. Thanks, will give it a shot.
2. When rendering. One of possible solutions for pdfjs is described [here](https://www.gyrocode.com/articles/how-to-increase-print-quality-of-pdf-file-with-pdf-js-viewer/)

**Comment by hrynko** [comment]
Ok, I will update the documentation for the next release, but if there is anything you want to add in the meantime – PRs are welcome.

As for the resolution issue, could you prepare an example to demonstrate it or at least a screenshot?

**Comment by Fuzzy-Supernova** [comment]
I've picked the pdf file which still had some fonts displayed for this comparison. The first [screenshot](https://i.ibb.co/3F4VZGz/image-5.png) is the file rendered without cMapUrl provided. The second [screenshot](https://i.ibb.co/6vC7TxF/image-6.png) is a fully rendered one. As you can see, both lines (especially the horizontal ones) and fonts look slightly different. @hrynko thanks for the help!

**Comment by hrynko** [comment]
Hi @Fuzzy-Supernova,

I will be preparing a new release soon. Would you like to update the README file with the info about CMaps?

I would appreciate your PR, if you have time for this.

**Comment by hrynko** [comment]
Never mind, I've updated the README in e316f3e
