### ISSUE TITLE
About the volume after packaging

### ISSUE THREAD

**Issue by sugar1999** [hrynko/vue-pdf-embed#144]
When building, the vue-pdf-embed.js file contains pdfjs code, which increases the size. At the same time, if the caller has a pdfjs package, it will contain a duplicate package

**Comment by hrynko** [comment]
Hi @sugar1999,

I'm going to provide more builds in the next minor release, so there will be options to load the lib with or without PDF.js (as mentioned in #128)

**Comment by hrynko** [comment]
See https://github.com/hrynko/vue-pdf-embed/issues/128#issuecomment-1912275958
