### ISSUE TITLE
supported svg

### ISSUE THREAD

**Issue by baixjian** [hrynko/vue-pdf-embed#145]
Thank you for producing such fascinating code, and I was thinking it would be great if this component supported svg

**Comment by hrynko** [comment]
Hi @baixjian,

Thanks for your feedback! What do you mean by SVG support?

**Comment by baixjian** [comment]
I'm sorry for not being clear enough. What I mean is whether the rendering mode of pdf can support canvas and svg

**Comment by hrynko** [comment]
Ah ok, got it now. I would consider this, but could you provide details on when it might be useful?

**Comment by baixjian** [comment]
Thank you for your reply. For example, in some mobile scenes, pdf needs to be scaled by hand. If it is canvas, the enlarged content will be a little fuzzy, but if it is rendered in svg mode, it will be very clear, which is my point.

**Comment by baixjian** [comment]
> Ah ok, got it now. I would consider this, but could you provide details on when it might be useful?

Do you have a plan to support svg rendering mode, or do you think svg mode is necessary？Looking forward to your reply。

**Comment by hrynko** [comment]
Hi @baixjian,

I opened a PR introducing the SVG render mode (#162). However, I highly doubt it, since this renderer has many issues, and many sources do not recommend it at all. Could you please check if it does its job for you?

PS: If it's just about clarity when scaling, it can be adjusted using custom `width`, `height`, and `scale` props

**Comment by baixjian** [comment]
> Hi @baixjian,
> 
> I opened a PR introducing the SVG render mode (#162). However, I highly doubt it, since this renderer has many issues, and many sources do not recommend it at all. Could you please check if it does its job for you?
> 
> PS: If it's just about clarity when scaling, it can be adjusted using custom `width`, `height`, and `scale` props

Thank you for your reply, I will read your code carefully
