### ISSUE TITLE
Event loading-failed return undefined

### ISSUE THREAD

**Issue by MSupachai** [hrynko/vue-pdf-embed#146]
Hello, I see that have emit event for 'loading-failed' to handle error while load PDF.
In my case I load PDF from url and try to handle if url is response 400. The emit is work fine but it return undefined.

![Screenshot 2566-06-19 at 15 45 48](https://github.com/hrynko/vue-pdf-embed/assets/100562730/2185f693-27d8-4348-8d1f-12587ca6ea31)

I try with new project and from the example but it didn't work too. But if I download this repo and run it it work.
This is error from download repo that it should be.
 
![Screenshot 2566-06-19 at 15 40 20](https://github.com/hrynko/vue-pdf-embed/assets/100562730/6c885489-e4eb-4a4b-b521-0886d450683d)

This is fiddle project that loading-failed return undefined.(I try to edit the url for case 400)
https://jsfiddle.net/8741qzLf/2/

**Comment by hrynko** [comment]
Hi @MSupachai,

I haven't been able to reproduce this, although you can try `vue-pdf-embed@2`, the problem may already be resolved there
