### ISSUE TITLE
how to rerender vue-pdf-embed?

### ISSUE THREAD

**Issue by ceative** [hrynko/vue-pdf-embed#147]
Hi
I have multiple pdf record  on table

 first time it is work, i click first record on table  it will render on  the modal
but  i click to another record on table, it is not render on the modal

**Comment by dmarcelotbp** [comment]
Have you solved this issue? I'm encountering the same thing.

**Comment by hrynko** [comment]
Please try to update the library to `v2.0.0`. After a few memory usage optimizations and changing the bundler, the problem may have already been solved. Otherwise, feel free to reopen the issue.
