### ISSUE TITLE
How to print all and preview it in pages？

### ISSUE THREAD

**Issue by ipbear** [hrynko/vue-pdf-embed#148]
I used ElementUI's pagination plugin to do pagination, and set page in <vue-pdf-embed :source="source1" :page="page" ref="printPdf" />, so that you can click on that page to display that page, but in this case, when using the print method, only 1 page of pdf can be printed, how can I print all pdf?

**Comment by hrynko** [comment]
Hi @ipbear,

Please see [print method signature](https://github.com/hrynko/vue-pdf-embed#public-methods) – 3rd argument is for printing all pages
