### ISSUE TITLE
What is the cause of the blurred display

### ISSUE THREAD

**Issue by lw230888794** [hrynko/vue-pdf-embed#151]
On the left is a display of the components，On the right is a normal display of clarity
![图片](https://github.com/hrynko/vue-pdf-embed/assets/76515476/37e5b73c-90cd-4924-a229-527d5482a088)

Here is the code

![图片](https://github.com/hrynko/vue-pdf-embed/assets/76515476/f0f4de9e-dabc-4d8a-b34d-43ba6af42982)

**Comment by hrynko** [comment]
Hi @lw230888794,

By default, the optimal scale is used, at which the image may appear blurry. To improve clarity, you can adjust the `scale` prop, but be aware that performance may suffer.
