### ISSUE TITLE
Embedded blob pdf with password restriction doesn't show the password input

### ISSUE THREAD

**Issue by kenichii** [hrynko/vue-pdf-embed#159]
The page is getting white blank page on pdf content

`<vue-pdf-embed
  v-if="document_file_readable_src_map"
  id="document-details-vue-pdf"
  :source="getDocumentFile"
  password-requested
  :rotation="pdf_data.rotation"
  @rendered="
    () =>
      pdfRender(
        getPDFDOMs.containerPDFElement,
        getPDFDOMs.canvasPDFElement
      )
  "
  :style="{ padding: '0 20px' }"
/>`

**Comment by hrynko** [comment]
Hi @kenichii,

To be able to display password-protected PDFs, you need to handle the `password-requested` event. Below is a minimal example of handling it:

```vue
<template>
  <vue-pdf-embed
    :source="pdfSource"
    @password-requested="handlePasswordRequest"
  />
</template>

<script>
export default {
  data() {
    return {
      pdfSource: '<PDF_URL>',
    }
  },
  methods: {
    handlePasswordRequest(callback, retry) {
      callback(prompt(retry
        ? 'Enter password again'
        : 'Enter password'
      ))
    },
  },
}
<script>
```

It is also available in the JSFiddle example: https://jsfiddle.net/hrynko/we7p5uq4

**Comment by kenichii** [comment]
I see, is it possible to make it inside the embedded? instead of promp

**Comment by kenichii** [comment]
I see, is it possible to make it inside the embedded? instead of promp @hrynko

**Comment by hrynko** [comment]
It is, however, it should be part of the client UI, not the library

**Comment by kenichii** [comment]
Do you have sample on how i can handle it? should i use toggle to display a component? not just sure how i can use the callback when user provided the password in the component

**Comment by kenichii** [comment]
I'm hoping the library has a slot that can display the password input instead. like this

```
<vue-pdf-embed
  v-if="document_file_readable_src_map"
  id="document-details-vue-pdf"
  :source="getDocumentFile"
  @password-requested="handlePasswordRequest"
  :rotation="pdf_data.rotation"
  @rendered="
    () =>
      pdfRender(
        getPDFDOMs.containerPDFElement,
        getPDFDOMs.canvasPDFElement
      )
  "
  :style="{ padding: '0 20px' }"
>
 <template slot="show-password">
  .....
 </template>
</vue-pdf-embed>
```

**Comment by hrynko** [comment]
Unfortunately, I don't have a sample. It depends on your UI, you can use `v-show` for hiding the PDF component while handling the password.

As for the slot, I don't see much point in it, since when the PDF is not rendered, it's just an empty div.

**Comment by kenichii** [comment]
May I know how I can trigger the callback to send the password when a user added the password?

**Comment by kenichii** [comment]
i tried this way, but not sure what i missed
```
handlePasswordRequest(callback) {
  if(callback(this.pdfPassword)) {
    this.showPassword = false;
  } else {
    this.showPassword = true;
  }
}
```

**Comment by kenichii** [comment]
it worked this way @hrynko however, i cant identify now if the password is correct or not
```
handlePasswordRequest(callback) {
  if(this.pdfPassword === "") {
    this.showPassword = true;
  }
  callback(this.pdfPassword);
  this.pdfPassword = "";
}
```

**Comment by hrynko** [comment]
When `password-requested` triggered for the first time, it only emits a callback function. If the provided password is incorrect, it will emit a callback function and a retry flag (boolean).

**Comment by kenichii** [comment]
i tried checking the`handlePasswordRequest(callback, retry)` flag but i always get false even the password is correct

**Comment by hrynko** [comment]
Exactly, consider using `v-show`

**Comment by kenichii** [comment]
ok sure, my only problem now is that it is showing the pdf already even i didnt set the password.
