### ISSUE TITLE
Any plans to support pdfjs v3?

### ISSUE THREAD

**Issue by clinsted** [hrynko/vue-pdf-embed#163]
At the time of this post the latest version is 3.11.174

**Comment by markus-ebner** [comment]
That would be great because we have some problems to show some PDF with included TIFF images with the major version 2. That problem seems to be solved with the version 3 of it since we tried it out in a pdf viewer with one of the newest versions.

**Comment by pyramid-johng** [comment]
I've been poking around at this project https://github.com/escape-llc/pdf-component-vue it uses PDFJS v3 maybe it fits your needs.

**Comment by hrynko** [comment]
The pdf.js dependency has been updated to `v3.11.174` in `v2.0.0`
