### ISSUE TITLE
 Use of eval in "node_modules/.pnpm/vue-pdf-embed@1.2.1_vue@3.3.4/node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### ISSUE THREAD

**Issue by jesephan** [hrynko/vue-pdf-embed#164]
Hi, Im using nuxtjs and added vue-pdf-embed as our dependency. However we have this warning during production build. Wondering how we can solve this? I'm using the latest `v1.2.1`of vue-pdf-embed.

**Comment by johnkristijan** [comment]
![image](https://github.com/hrynko/vue-pdf-embed/assets/33238136/0bc1d685-510f-41e5-ae09-83510ca62168)
Same error for me.
Using `"vue-pdf-embed": "^1.2.1",`
Stack: Vue3 + Vite

**Comment by hrynko** [comment]
Hi @jesephan @johnkristijan,

I'm on it. Unfortunately, I don't have a solution right now, but I'll let you know when I do.

**Comment by jesephan** [comment]
Hello @hrynko, I totally appreciate your effort of finding the solution to this. Thank you!

**Comment by xiaoxian521** [comment]
Question source answer：https://github.com/mozilla/pdf.js/issues/16061#issuecomment-1453878282

**Comment by hrynko** [comment]
Please check https://github.com/hrynko/vue-pdf-embed/issues/90#issuecomment-1902100099. I tried to address this issue in `v2.0.0`, however still not sure if it will be resolved.
