### ISSUE TITLE
Error loading font

### ISSUE THREAD

**Issue by ChYuanJinlin** [hrynko/vue-pdf-embed#168]
GET https://unpkg.com/browse/pdfjs-dist@3.11.174/cmaps/UniGB-UCS2-H 404

Warning: loadFont - translateFont failed: "r: Unable to load CMap at: https://unpkg.com/browse/pdfjs-dist@3.11.174/cmaps/UniGB-UCS2-H".

Warning: Error during font loading: Unable to load CMap at: https://unpkg.com/browse/pdfjs-dist@3.11.174/cmaps/UniGB-UCS2-H

**Comment by Jsharkc** [comment]
I'm having the same problems，did you solve it
