### ISSUE TITLE
The PDF clarity after loading is significantly lower than the iframe loading method.

### ISSUE THREAD

**Issue by lsdt45** [hrynko/vue-pdf-embed#169]
the result of vue-pdf-embed：
![Snipaste_2023-10-20_10-56-36](https://github.com/hrynko/vue-pdf-embed/assets/42729729/f57a9d62-0ad7-4cf5-9265-f2d0224a8294)

the result of <iframe>:
![2](https://github.com/hrynko/vue-pdf-embed/assets/42729729/1e9f8ded-3b5b-4a0a-aef6-b119bbcacc12)

How to improve clarity？

**Comment by hrynko** [comment]
Hi @lsdt45,

You can adjust this with the [scale](https://github.com/hrynko/vue-pdf-embed#props) prop (see https://github.com/hrynko/vue-pdf-embed/issues/151#issuecomment-1729461385)
