### ISSUE TITLE
Print all sheets of paper

### ISSUE THREAD

**Issue by GitHubPhongNguyen** [hrynko/vue-pdf-embed#176]
I have 1 file pdf on server and when i preview or download to preview i see 2 pages with order like this:
- page 1: have content
- page 2: have content

But when i print this file i saw 3 sheets of page with order like this:
- page 1: have content
- page 2: empty page
- page 3: have content
I use Vue2 and update check i see have and error with pdf 1.5

**Comment by hrynko** [comment]
Hi @GitHubPhongNguyen,

Could you share the document you are having trouble with?
