### ISSUE TITLE
vue3 预览pdf出现白屏

### ISSUE THREAD

**Issue by leishenws** [hrynko/vue-pdf-embed#180]
<img width="1257" alt="Snipaste_2024-01-27_22-09-15" src="https://github.com/hrynko/vue-pdf-embed/assets/95082567/42f4d525-02de-4a8c-ba8f-a4cabb27828d">
vue3 预览pdf出现白屏

**Comment by hrynko** [comment]
Hi @leishenws,

I guess you're using the essential build, thus you must either switch to the regular build or use the `v3.11.174` worker (as it comes from the error message).
