### ISSUE TITLE
vue-pdf-embed fails to make http call to retrieve pdf document

### ISSUE THREAD

**Issue by isaacssemugenyi** [hrynko/vue-pdf-embed#182]
This happens when CSP headers are configured and 'unsafe-eval' not added in the script-src. 

`Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). [df14d96a-85dd-4d9e-9104-ccebec29bcbb:1:20259](blob:http://localhost/df14d96a-85dd-4d9e-9104-ccebec29bcbb)
EvalError: call to Function() blocked by CSP [df14d96a-85dd-4d9e-9104-ccebec29bcbb:1:20259](blob:http://localhost/df14d96a-85dd-4d9e-9104-ccebec29bcbb)
    e blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1
    n blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1
    636 blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1
    r blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1
    <anonymous> blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1
    <anonymous> blob:https://<url>/df14d96a-85dd-4d9e-9104-ccebec29bcbb:1`

**Comment by hrynko** [comment]
Hi @isaacssemugenyi,

Just to confirm, which version of `vue-pdf-embed` are using? Have you tried the essential build (see [README](https://github.com/hrynko/vue-pdf-embed#web-worker-loading))?

**Comment by isaacssemugenyi** [comment]
> Hi @isaacssemugenyi,
> 
> Just to confirm, which version of `vue-pdf-embed` are using? Have you tried the essential build (see [README](https://github.com/hrynko/vue-pdf-embed#web-worker-loading))?

I am using   "vue-pdf-embed": "^1.2.1", since it is a legacy system that is not upgraded to v3. However I managed to make it work by using unsafe-*** in my CSP headers for script-src and blob: in image-src.

**Comment by hrynko** [comment]
Ok, good that you got over it

And I think this is the only way to handle this in `v1` so far

**Comment by sluxzer** [comment]
Hi @isaacssemugenyi 

I had the same issue as yours, could you please share your fixed here 

Thanks
