### ISSUE TITLE
text-layer is broken since version 2.0.0

### ISSUE THREAD

**Issue by felixwortmann** [hrynko/vue-pdf-embed#184]
Adding a text layer shows the text below the rendered pdf element. 

Can be reproduced by adding `text-layer:"true"` to the jsfiddle example as I did here: https://jsfiddle.net/qb8d5wmu/

I could only find the error in versions 2.x.x so I am pretty sure that it was introduced in 2.0.0

**Comment by hrynko** [comment]
Hi @felixwortmann,

Since `v2.0.0`, styles must be manually imported. For the text layer it is `vue-pdf-embed/dist/style/textLayer.css`.
