### ISSUE TITLE
Dealing with multiple blank pages when printing documents

### ISSUE THREAD

**Issue by ljh-coder** [hrynko/vue-pdf-embed#188]
Hi, I found a problem when I use the print function, there is a blank page in the print preview every time, but when I test the sample file [compressed.tracemonkey-pldi-09.pdf](https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf), there is no blank page. Later, I refer to some information on the Internet and modified the `margin` style of the `addPrintStyles` method in the `src/utils.ts` file and found that the blank page disappeared.

`src/utils.ts`:

```js
export function addPrintStyles(
  iframe: HTMLIFrameElement,
  sizeX: number,
  sizeY: number
) {
  const style = iframe.contentWindow!.document.createElement('style')
  style.textContent = `
    @page {
      //   margin: 0;

      // Modify the parameter to 3mm
      margin: 3mm;

      size: ${sizeX}pt ${sizeY}pt;
    }
    body {
      margin: 0;
    }
    canvas {
      width: 100%;
      page-break-after: always;
      page-break-before: avoid;
      page-break-inside: avoid;
    }
  `
  iframe.contentWindow!.document.head.appendChild(style)
  iframe.contentWindow!.document.body.style.width = '100%'
}
```

before modification:

![1](https://github.com/hrynko/vue-pdf-embed/assets/62947861/3c249872-97c5-4b3c-a26b-46eec314f808)

after modification:

![2](https://github.com/hrynko/vue-pdf-embed/assets/62947861/6f2f3ee1-ba9c-4fd5-bc21-0c4a77aa858f)

My test file: [2021.06.pdf](https://github.com/hrynko/vue-pdf-embed/files/14354488/2021.06.pdf)

Reference Blog: <https://blog.csdn.net/qq_42249552/article/details/112860593>

**Comment by hrynko** [comment]
Hi @ljh-coder,

Looks like a fix, but why the 3mm margin (I still cannot get it from the reference)?

PS: I would appreciate you opening a PR

**Comment by ljh-coder** [comment]
> 嗨，
> 
> 看起来像一个修复，但为什么是 3 毫米的边距（我仍然无法从参考中得到它）？
> 
> PS：我希望你打开一个PR

As to why modifying the style fixed the problem, I'm not really sure, and the reference link doesn't state that, it just points out that the problem is with the style, and I tried modifying the `margin` attribute and the problem was solved.
I tried to submit a PR, and since it's my first time, I may not have done a very good job, is there anything else I should add?

**Comment by SivonLi** [comment]
@hrynko The same issue occurs in the Vue 2 version.

**Comment by SivonLi** [comment]
#[export function addPrintStyles(iframe, sizeX, sizeY) {
  const style = iframe.contentWindow.document.createElement('style')
  style.textContent = `
    @page {
      margin: 0;
      size: ${sizeX}pt ${sizeY}pt;
    }
    body {
      margin: 0;
    }
    canvas {
      width: 100%;
      page-break-after: always;
      page-break-before: avoid;
      page-break-inside: avoid;
    }
  `
  iframe.contentWindow.document.head.appendChild(style)
  iframe.contentWindow.document.body.style.width = '100%'
}](https://github.com/hrynko/vue-pdf-embed/blob/4430386bb73b2d117450aec2beefa53435717516/src/util.js#L1-L20)
@hrynko The v1 version also has the same issue.
