### ISSUE TITLE
how to call local assets pdf

### ISSUE THREAD

**Issue by myomyintaung1411** [hrynko/vue-pdf-embed#19]

**Comment by hrynko** [comment]
Hi @myomyintaung1411,

I'm not sure I get the point. Can you please describe the issue in more detail?

**Comment by myomyintaung1411** [comment]
hello sir, Here i want to add source from my assets folder not from api
 <vue-pdf-embed :source="source1" />

**Comment by hrynko** [comment]
You can use the component as follows if you store `mypd.pdf` in static (public) directory:

```html
<vue-pdf-embed source="/assets/mypd.pdf" />
```

**Comment by hrynko** [comment]
I hope that helped, and I'm closing the issue. Feel free to reopen it if needed.

**Comment by mattesalva93** [comment]
Hi,

i'm currently trying to access a local pdf file but it seems it doesn't work the way you provided:

`<vue-pdf-embed source="/assets/PDF/mypdf.pdf" />`

Doing it this way doesn't work, it returns a GET error 404.
