### ISSUE TITLE
Security: unsafe-eval - Need CSP solution for Vue 2

### ISSUE THREAD

**Issue by sluxzer** [hrynko/vue-pdf-embed#190]
Hi Everyone

I believe this problem has been resolved in vue 3 and the solution is documented in [Readme]( https://github.com/hrynko/vue-pdf-embed?tab=readme-ov-file#common-issues-and-caveats)

My Problem: 
- PDF cannot be previewed due to the usage of the eval function when enabling Content Security Policy with script-src 'self'. To overcome this issue, unsafe-eval must be added, which would only increase security vulnerabilities.
- This CSP rule is added via the backend
<img width="1440" alt="image" src="https://github.com/hrynko/vue-pdf-embed/assets/5717315/90f8ae9d-d293-4502-a21b-4cdfb9a6e372">

Related Ticket: 
#53 #90 

Is there any alternative solution that I can implement on Vue 2?

Requirements:
- vue-pdf-embed: 1.1.4
- Vue - 2.**
- Browser - Firefox/Chrome

**Comment by hrynko** [comment]
Hi @sluxzer,

Unfortunately, there is no alternative solution for Vue 2 so far

**Comment by sluxzer** [comment]
Hi @hrynko  

Could you tell me any possible way to fix this?

I mean, we were ready to make an exception for this page.

But it would be even great if somehow I could contribute to custom the lib, I just need your thought if it's worth it? 🙏


Anyway, thank you for such a fast response. It really helps us to make decisions.

**Comment by hrynko** [comment]
Well, my efforts are now focused on the version 2 of the library. Thus, I am unlikely to be able to address this issue anytime soon. If you have the ability to do so, I would really appreciate it, but at this point a policy adjustment on your side seems like the best course of action.

**Comment by sluxzer** [comment]
@hrynko  Thank you for your answer, let me close this ticket for now until further progress. 

Best of luck!
