### ISSUE TITLE
Files imported through cdn cannot be displayed; Vite + Vue3

### ISSUE THREAD

**Issue by sea-caterpillar** [hrynko/vue-pdf-embed#191]
Environment:

- Vue Version: 3.3.0

- vue-pdf-embed Version: 2.0.0、2.0.2

- UserAgent:  Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36

- Build Tool: Vite

Code Snippet:

![image](https://github.com/hrynko/vue-pdf-embed/assets/25836014/35b339ed-9137-462d-8937-183c33f51fca)
![image](https://github.com/hrynko/vue-pdf-embed/assets/25836014/ec0ee6d0-205a-40d7-ad7e-16c33e330cc4)
![image](https://github.com/hrynko/vue-pdf-embed/assets/25836014/5ee6a322-689e-4287-81ec-eb9d4b4b024f)
![image](https://github.com/hrynko/vue-pdf-embed/assets/25836014/ef5a01b0-a0b7-4b2d-824b-e2468145769e)
![image](https://github.com/hrynko/vue-pdf-embed/assets/25836014/69253f37-e2ed-43bf-a80f-1c5a3a46b34a)

Rendering-failed:

    TypeError: Cannot read properties of undefined (reading 'children')
       at index.umd.js:28:3543
       at async Promise.all (:5173/index 0)
       at async G (index.umd.js:28:3387)

Files imported through cdn cannot be displayed; 

But the other way is normal; 
eg: `npm install vue-pdf-embed import VuePdfEmbed from 'vue-pdf-embed'`
 
How to solve, please help me;

**Comment by mynameismaosheng** [comment]
How did you solve it?

**Comment by Linkodt** [comment]
How did you solve it?

**Comment by guifw** [comment]
@mynameismaosheng @Linkodt 
I solved it.
`
import * as V from 'vue';

window.vue = V;
window.Vue = V;
`
