### ISSUE TITLE
loading large pdf show errors 

### ISSUE THREAD

**Issue by lxxSylophone** [hrynko/vue-pdf-embed#192]
Warning: loadFont - translateFont failed: "r: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.".

**Comment by lxxSylophone** [comment]
Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.

**Comment by hrynko** [comment]
Hi @lxxSylophone,

Please check [README](https://github.com/hrynko/vue-pdf-embed#resources)
