### ISSUE TITLE
Loading failed with undefined as error

### ISSUE THREAD

**Issue by ramseyfeng** [hrynko/vue-pdf-embed#195]
I'm using vue2 + vue-embeded-pdf(1.2.1), when i try to preview a pdf which size is around 10Mb.
I got an the loading-error event with undefined return, meanwhile, i got below warning, not sure if it is caused by those warnings.

```
Warning: Indexing all PDF objects
vue2-pdf-embed.js:1 Warning: DocException - expected a valid Error

```
<img width="561" alt="image" src="https://github.com/hrynko/vue-pdf-embed/assets/2835062/3f35d9ff-28d3-427d-90f0-158a390d7556">

**Comment by bryandidur** [comment]
Same here

**Comment by ramseyfeng** [comment]
Closed the issue, since it was caused by an invalid PDF document.

**Comment by Piscando** [comment]
![image](https://github.com/hrynko/vue-pdf-embed/assets/77775020/66f0b853-937e-4c36-b5ed-806652704aec)

**Comment by Piscando** [comment]
pdf显示不出来
