### ISSUE TITLE
An error occurs when IE11 is running  vue2+cli-service5

### ISSUE THREAD

**Issue by shihaohaoshiwo** [hrynko/vue-pdf-embed#197]
I want to know if this plugin supports IE11?
![image](https://github.com/hrynko/vue-pdf-embed/assets/51901729/7da2c21c-6619-4f2b-9c0e-48334b745e8d)
![image](https://github.com/hrynko/vue-pdf-embed/assets/51901729/c3e0a4d1-8f4d-4804-bd45-32304daf726b)
![image](https://github.com/hrynko/vue-pdf-embed/assets/51901729/0f0185bc-d1ce-413a-8666-43f772bec80c)

**Comment by hrynko** [comment]
Hi @shihaohaoshiwo,

Can you confirm that this is issue is IE11 specific (i.e. not reproducible in other browsers)? If so, could you try logging `loading-failed` and `rendering-failed`?

**Comment by hrynko** [comment]
Hi @shihaohaoshiwo,

Feel free to reopen the issue with more details. Answering your previous question, this library supports IE11 in versions 1.x when used with Vue 2.
