### ISSUE TITLE
using  vue-pdf-embed with vue+ts+vite    when rendering multi-page pdf and specify that page cannot be rendered

### ISSUE THREAD

**Issue by CCCoooolll** [hrynko/vue-pdf-embed#198]
<vue-pdf-embed
        v-for="(item, index) in pdfState.numPages"
        :key="index"
        :page="index"
        :source="pdfState.pdfSource"
        textLayer
        :style="{
          transform: `translateX(-50%) `,
          marginLeft: '50%',
          width: '100%',
        }"
        @rendered="handleRendered"
        @rendering-failed="handleRenderFiled"
      />

must set page and  use v-for to render

**Comment by hrynko** [comment]
Hi @CCCoooolll,

Sorry, I'm not sure I understand the question. Could you try to paraphrase?
