### ISSUE TITLE
vue-pdf-embed v1.2.1 - Performance issue with large PDF files

### ISSUE THREAD

**Issue by franck-grenier** [hrynko/vue-pdf-embed#199]
Hello,
I'm using vue-pdf-embed to render PDF files on a Web page and I'm experiencing performance issues when I display large files (~250 pages).

When displaying my page, PDF rendering works but memory and CPU usage increase crazily up too 100% and crashes my browser. That can even freeze my whole system.

Do you know anything about that behaviour ?

Thanks

**Comment by hrynko** [comment]
Hi @franck-grenier,

I am constantly trying to improve the library performance, but displaying a large number of pages at the same time is a problem beyond the library's capabilities. Partial display of the document or lazy loading of pages can be options to solve this problem. So I've prepared minimal examples of lazy loading implementation for [v1](https://jsfiddle.net/hrynko/6eL38bof/) and [v2](https://jsfiddle.net/hrynko/u149my7h/).
