### ISSUE TITLE
How to view two pages at a time?

### ISSUE THREAD

**Issue by Sonik20** [hrynko/vue-pdf-embed#2]

**Comment by hrynko** [comment]
Hi @Sonik20!

You can add 2 sequential components:

```
<vue-pdf-embed :source="pdfSource" :page="1" />
<vue-pdf-embed :source="pdfSource" :page="2" />
```

Or omit the `page` property if the file consists of 2 pages:

```
<vue-pdf-embed :source="pdfSource" />
```

**Comment by Sonik20** [comment]
This helps.

I am facing another issue, getting 403 forbidden error in the url of the pdf which is an azure blob, the URL has CORS set still the error.

**Comment by hrynko** [comment]
If the document has limited access, try loading it manually and providing it as a typed array (see README.md). If CORS is the issue, try adjusting the server config.

**Comment by hrynko** [comment]
> This helps.

I'm closing the issue since the original question has been resolved. Hopefully, the follow-up question too.

Feel free to open new issues if you need further help.
