### ISSUE TITLE
V2 Rendering quality issues compared to 1.2.1

### ISSUE THREAD

**Issue by cronco** [hrynko/vue-pdf-embed#201]
I am trying to mitigate some of the issues uncovered as part of #199 by using v2 of the library, however for some documents I am observing a marked difference in rendering quality.

Screenshot from stackblitzes that highlight the issue:
* Version 1.2.1 output below:
![Screenshot 2024-03-26 at 12 20 45](https://github.com/hrynko/vue-pdf-embed/assets/530000/d7d17618-9743-4fdb-b418-807ff4bd2a1e)
* Version 2.0.3 output below:
![Screenshot 2024-03-26 at 12 20 58](https://github.com/hrynko/vue-pdf-embed/assets/530000/e92f7760-34e5-4f28-9cc3-39a5dd78dec3)

Notice the artefacts around the text in the table. This is on page 12 of the document in the example.

Stackblitz links:
* Version [1.2.1](https://stackblitz.com/edit/vue-pdf-embed-pqtnj7)
* Version [2.0.3](https://stackblitz.com/edit/vue-pdf-embed-d6zseo)

The one potential cause I see for this is in the viewport dimensions being passed down to the canvas. See the difference in dimensions between v.1.2.1 and v2.0.3 here:

![Screenshot 2024-03-26 at 12 27 06](https://github.com/hrynko/vue-pdf-embed/assets/530000/4905eb83-e459-4f12-b2b7-c8fdf9df88cd)
![Screenshot 2024-03-26 at 12 27 38](https://github.com/hrynko/vue-pdf-embed/assets/530000/d46938bc-1165-4af3-b2e4-0833373c55c2)
As you can see, v1.2.1 calculates a width of 2880 and a height of 1620 for the canvas, whereas v2.0.3 uses the same height and width as the css values.

Where it gets interesting is that even if I manually set the canvas size to 2880 and then resize it through CSS to 1400, I get a large degradation in quality (see final screenshot)
![Screenshot 2024-03-26 at 12 34 59](https://github.com/hrynko/vue-pdf-embed/assets/530000/e40baf7b-cb5b-4032-bcce-dcd237dc0664)

I've also tried manually setting the scaling up, down etc. and nothing seems to work. Any help would be appreciated.

**Comment by cronco** [comment]
I've done a little more digging and it seems this is due to a regression in pdf.js itself, introduced somewhere between 2.10.377 and 2.11.338, as can be seen in these two variants of this js fiddle:
* [Version 2.10.377](https://jsfiddle.net/cronco/rcqwy5xv/29/)
* [Version 2.11.338](https://jsfiddle.net/cronco/rcqwy5xv/28/)

**Comment by hrynko** [comment]
Hi @cronco,

So do you think any action should be taken on the `vue-pdf-embed` part?

**Comment by cronco** [comment]
@hrynko the pdf.js maintainers have been quick to point out that the issue seemed to be with the pdf file itself - the part of the file that was rendered less well defined in the new version was an image with the `/Interpolation` setting set to false, which meant no smoothing was done when upscaling it. I think we can close the ticket, thanks for checking.!
