### ISSUE TITLE
vue3 中 pdf 内容错乱

### ISSUE THREAD

**Issue by xz719** [hrynko/vue-pdf-embed#208]
当我在 vue3 中使用该插件时，我通过 pages 变量控制插件的展示方式，当 pages 传入 null 时，展示所有页面；当传入具体的值时，展示 pdf 的某一页。（实际上就是与[官方提供的 demo](https://jsfiddle.net/hrynko/273a59qr) 中一样的用法）。

但当我先展示所有页面，然后切换为每次展示一页并向后翻页，最后再切换回展示所有页面时，pdf 的内容会出现错乱，这个问题在官方提供的 demo 中同样存在。

![1](https://github.com/hrynko/vue-pdf-embed/assets/84949554/dd5b004e-8197-4189-925e-9491057d5b0f)

**Comment by hrynko** [comment]
Hi @xz719,

Thanks for reporting this issue, I'll try to address it in the next release

**Comment by hrynko** [comment]
`v2.1.0` containing a fix for this issue has been released
