### ISSUE TITLE
Self in not defined in Nuxt.js

### ISSUE THREAD

**Issue by Beisenbayev** [hrynko/vue-pdf-embed#21]
![image](https://user-images.githubusercontent.com/69448982/162368829-8c080acc-3252-4424-8dcc-7d5e22b25d54.png)

**Comment by hrynko** [comment]
Hi, can you check if your issue has been resolved in 5?

**Comment by hrynko** [comment]
Hi, can you please check if you can solve the problem as in #12?

**Comment by Beisenbayev** [comment]
> Hi, can you please check if you can solve the problem as in #12?

Hi, the author of this issue left a comment about solving the problem, but I don't understand what exactly needs to be done?
https://github.com/hrynko/vue-pdf-embed/issues/12#issuecomment-1058400917

**Comment by Beisenbayev** [comment]
**Solution:**
1) You have to create a vue-pdf-embed.js file inside the plugins folder in your  project.
  |-plugins
    |-vue-pdf-embed.js

2) In this file import Vue and vue-pdf-embed (_The problem was because of this step. Make make sure about your version of nuxt. If you are using Nuxt3 (vue3) - then import from vue-pdf-embed_)
  vue-pdf-embed.js:
```
    import Vue from 'vue'
    import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'
    Vue.use(VuePdfEmbed)
    Vue.component('vue-pdf-embed', VuePdfEmbed)
```

3) In nuxt.config.js file you have a plugins array. Add this line to inside an array: ([more about](https://nuxtjs.org/docs/configuration-glossary/configuration-plugins/))
    `{ src: '~/plugins/vue-pdf-embed.js', ssr: false, mode: 'client' }`

**Comment by getshaun24** [comment]
> **Solution:**
> 
> 1. You have to create a vue-pdf-embed.js file inside the plugins folder in your  project.
>    plugins:
>    |-vue-pdf-embed.js
> 2. In this file import Vue and vue-pdf-embed (_The problem was because of this step. Make sure about your version of nuxt. If you are using Nuxt3 (vue3) - then import from vue-pdf-embed_)
> 
> vue-pdf-embed.js:
> 
> ```
>     import Vue from 'vue'
>     import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'
>     Vue.use(VuePdfEmbed)
>     Vue.component('vue-pdf-embed', VuePdfEmbed)
> ```
> 
> 3. In nuxt.config.js file you have a plugins array. Add this line to an array: ([read more](https://nuxtjs.org/docs/configuration-glossary/configuration-plugins/))
>    `{ src: '~/plugins/vue-pdf-embed.js', ssr: false, mode: 'client' }`

Thank you for the solution but I am still getting the self not defined issue.



this is my vue-pdf-embed.js file

`import Vue from 'vue'
import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'
Vue.use(VuePdfEmbed)
Vue.component('vue-pdf-embed', VuePdfEmbed)`


and this is in my vue file

`<script>
import VuePdfEmbed from 'vue-pdf-embed'

// OR THE FOLLOWING IMPORT FOR VUE 2
// import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'

export default {
  components: {
    VuePdfEmbed,
  },
  data() {
    return {
      source1: '../../public/xxx.pdf',
    }
  },
}
</script>`


Please can somebody help?! 

Thank You :)

**Comment by abdmdjr** [comment]
In Nuxt 3, create a file in /plugins and name it **vue-pdf-embed.client.ts**

```
import VuePdfEmbed from "vue-pdf-embed";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("vue-pdf-embed", VuePdfEmbed);
});
```

In your page/component, use it like that :
`<vue-pdf-embed
    ref="pdfRef"
    :source="post.file"
    :page="page"
    @rendered="handleDocumentRender"
/>`

**Comment by ekrausso** [comment]
this worked for me:

```
// plugins/vue-pdf-embed.client.ts

export default defineNuxtPlugin( nuxtApp => {
    const vuePdfEmbed = defineAsyncComponent(() => import('vue-pdf-embed'))
    nuxtApp.vueApp.component("vue-pdf-embed", vuePdfEmbed)
})
```

**Comment by th4it4y4** [comment]
I got this problem too in NuxtJs 2. So I add " { src: '~/plugins/vue-pdf-embed.js', ssr: false, mode: 'client' } " in my nuxt config and impost lib in script but it have error "Plugin not found"  plz help

**Comment by honghuynhit** [comment]
> **Solution:**
> 
> 1. You have to create a vue-pdf-embed.js file inside the plugins folder in your  project.
>    plugins:
>    |-vue-pdf-embed.js
> 2. In this file import Vue and vue-pdf-embed (_The problem was because of this step. Make sure about your version of nuxt. If you are using Nuxt3 (vue3) - then import from vue-pdf-embed_)
> 
> vue-pdf-embed.js:
> 
> ```
>     import Vue from 'vue'
>     import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'
>     Vue.use(VuePdfEmbed)
>     Vue.component('vue-pdf-embed', VuePdfEmbed)
> ```
> 
> 3. In nuxt.config.js file you have a plugins array. Add this line to an array: ([read more](https://nuxtjs.org/docs/configuration-glossary/configuration-plugins/))
>    `{ src: '~/plugins/vue-pdf-embed.js', ssr: false, mode: 'client' }`

Very detail. Big thanks

**Comment by terajoellang** [comment]
> I got this problem too in NuxtJs 2. So I add " { src: '~/plugins/vue-pdf-embed.js', ssr: false, mode: 'client' } " in my nuxt config and import lib in script but it have error "Plugin not found" plz help

Same issue here, did you find a solution?

**Comment by zguig52** [comment]
Quick and easy steps for Nuxt3 integration as a plugin:

1. Create a folder plugins

2. Create a file named VuePdfEmbed.client.js inside the folder with following content:
```
import VuePdfEmbed from 'vue-pdf-embed'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VuePdfEmbed)
  nuxtApp.vueApp.component('VuePdfEmbed', VuePdfEmbed);
})

```
3. Use it in your app like this:
<VuePdfEmbed :source="pdfURL" />

**Comment by hrynko** [comment]
HI @zguig52,

Could you duplicate your answer to #114?

**Comment by zguig52** [comment]
Done :)! I did not found this topic waiting for an answer
