### ISSUE TITLE
redundant render base64 pdf cause same canvas render multiple time error

### ISSUE THREAD

**Issue by kstan79** [hrynko/vue-pdf-embed#210]
Hi,

I'm using base64 string to load pdf, first load ok (i render within a dialog).after i close the dialog and open again it complaint render multiple time in same canvas.

![err1](https://github.com/hrynko/vue-pdf-embed/assets/1889979/7f0f978d-f83b-4237-b3dc-be1ad502e8ce)
![err2](https://github.com/hrynko/vue-pdf-embed/assets/1889979/d21cc79b-6a9e-4520-a945-4d83a3e33d46)

**Comment by jshamg** [comment]
+1 on this

**Comment by hrynko** [comment]
A fix for this issue has been released in `v2.1.0`. Thanks for reporting!
