### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by leeobrum** [hrynko/vue-pdf-embed#212]
Hi,

After I make the update in my project vue-pdf-embed  ^1.2.1  →  ^2.0.3. I recived this error:

# npm audit report

pdfjs-dist  <=4.1.392
Severity: high
PDF.js vulnerable to arbitrary JavaScript execution upon opening a malicious PDF - https://github.com/advisories/GHSA-wgrm-67xf-hhpq
fix available via `npm audit fix --force`
Will install vue-pdf-embed@1.2.1, which is a breaking change
node_modules/pdfjs-dist
  vue-pdf-embed  <=1.0.4 || >=2.0.0
  Depends on vulnerable versions of pdfjs-dist
  node_modules/vue-pdf-embed
  

Do you have any solution? Or am I doing something wrong?

**Comment by hrynko** [comment]
Resolved in #215

Thanks for reporting
