### ISSUE TITLE
images/cursor-editorInk.svg Image loading failed

### ISSUE THREAD

**Issue by wangxiaoze-view** [hrynko/vue-pdf-embed#222]
I used the webpack project to introduce the plug-in, but when I introduced the css, I found an error, saying that there were image resources introduced in the css, but no related images were found in the root directory;

But there is no related problem in vite, the versions are consistent and I don’t know what caused the problem;

I copied the css in the node_modules plugin and found this problem

``` css
--editorInk-editing-cursor: url(images/cursor-editorInk.svg) 0 16, pointer;
  --editorHighlight-editing-cursor: url(images/cursor-editorTextHighlight.svg) 24 24, text;
  --editorFreeHighlight-editing-cursor: url(images/cursor-editorFreeHighlight.svg) 1 18, pointer
```

![image](https://github.com/hrynko/vue-pdf-embed/assets/48245867/0f15ebe7-10f7-4651-897a-cdb70217fdc6)

But after I commented these out, there is no error. The page style is also displayed correctly. I am not sure if these comments will have any effect later?

**Comment by hrynko** [comment]
A supposed fix for this issue has been released in `v2.1.0`

Feel free to reopen if this doesn't solve the reported problem
