### ISSUE TITLE
support zooming gestures

### ISSUE THREAD

**Issue by baixjian** [hrynko/vue-pdf-embed#223]
Thank you for making such a perfect component, I was wondering if you have a plan to support the zooming display of gestures, which should be a lot in the mobile scene, thank you again.

**Comment by baixjian** [comment]
https://hammerjs.github.io/recognizer-pinch/
Do you think this is a good plan

**Comment by hrynko** [comment]
Hi @baixjian,

Thank you for your feedback and feature suggestion, but there are no plans to implement it at this time. This component is designed for embedding the PDF documents into web pages, and to keep it simple and performant I assume such view manipulations to be implemented on the application level.
