### ISSUE TITLE
SyntaxError: The requested module '/node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-3081220230817001_vue@3.2.47/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at index.mjs:20:47)

### ISSUE THREAD

**Issue by iamchenjing** [hrynko/vue-pdf-embed#224]
SyntaxError: The requested module '/node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-3081220230817001_vue@3.2.47/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at index.mjs:20:47)

**Comment by NicolaiHorlacher** [comment]
`vue-pdf-embed` requires `vue 3.3` because it uses the [toValue](https://vuejs.org/api/reactivity-utilities.html#tovalue) helper function.
Updating dependencies will probably fix your issue.

**Comment by iamchenjing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hrynko** [comment]
Indeed, thanks for clarifying @NicolaiHorlacher
