### ISSUE TITLE
npm packages deprecations

### ISSUE THREAD

**Issue by bci24** [hrynko/vue-pdf-embed#228]
I am using vue-pdf-embed: 2.0.4 (latest) and node: 20.15.1 (LTS) npm: 10.7.0 and vue 3 (latest)

In my project when install I receive some depracations (and seems that all the packages are relates to vue-pdf-embed):

npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.

C:\www\MyProject>npm ls are-we-there-yet@2.0.0
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- npmlog@5.0.1
          `-- are-we-there-yet@2.0.0

C:\www\MyProject>npm ls glob@7.2.3            
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- rimraf@3.0.2
          `-- glob@7.2.3

C:\www\MyProject>npm ls inflight@1.0.6
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- rimraf@3.0.2
          `-- glob@7.2.3
            `-- inflight@1.0.6

C:\www\MyProject>npm ls npmlog@5.0.1 
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- npmlog@5.0.1

C:\www\MyProject>npm ls rimraf@3.0.2  
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- rimraf@3.0.2

C:\www\MyProject>npm ls gauge@3.0.2
MyProject@ C:\www\MyProject
`-- vue-pdf-embed@2.0.4
  `-- pdfjs-dist@4.4.168
    `-- canvas@2.11.2
      `-- @mapbox/node-pre-gyp@1.0.11
        `-- npmlog@5.0.1
          `-- gauge@3.0.2`
`

Any updates?

**Comment by hrynko** [comment]
Hi @bci24,

The mentioned dependencies are not used directly in the project, but as sub-dependencies. I have plans to update some dependencies, although I'm not sure if that will help.
