### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by allmax666** [hrynko/vue-pdf-embed#234]
pdf.js support horizontal page scrolling. Maybe, this option will be useful in vue-pdf-embed

**Comment by hrynko** [comment]
Hi @allmax666,

I'm not sure if I'm understanding you correctly, but it seems to me that this is outside the lib scope and it's just a matter of page alignment or dimension adjustment. Feel free to reopen the issue if that's not the case.

**Comment by allmax666** [comment]
Hi @hrynko,

Thanks for the feedback
I mean horizontal placement of pdf document pages, like in the attached image.
I couldn't do it in this wonderful framework.
![horizontal_scroll](https://github.com/user-attachments/assets/2e995ef0-70a9-403f-bb4c-9e21aba90874)
