### ISSUE TITLE
Implement Vue 2 support for v2. 

### ISSUE THREAD

**Issue by gkweb** [hrynko/vue-pdf-embed#238]
Vue 2 support is still possible with some very very minor changes. 

Are you open to supporting both? 

I'd be happy to open a PR. This might see the folder structure change slightly to support both versions of Vue gracefully.

**Comment by gkweb** [comment]
@hrynko - Rough proposal before I spend any time there. See detail and let me know your thoughts? 

Workspaces set up in the repo

Vue 2 in workspace will sit in
`@vue-pdf-embed/vue2`

And consumed when published to npm via `vue-pdf-embed/vue2/*`
Vue 3 is consumed as normal under: `vue-pdf-embed/*`

_proposed folder change:_ 
- packages/
  - core
    - @vue-pdf-embed/core
    - current project and associated ts / .vue
    - The ONLY minor change to the vue implementation is to switch out `toValue` to `unref`
    - Types - Look at adding a checked in`MaybeRef` (doesn't exist for vue 2).
  - vue2 
    - @vue-pdf-embed/vue2
    - package.json
      - Will hold different Vue deps (vue 2) and vite build deps
      - will build output into `packages/vue2/dist` OR workspace root `/dist/vue2` TBC

**Comment by gkweb** [comment]
Friendly bump of that [proposal](https://github.com/hrynko/vue-pdf-embed/issues/238#issuecomment-2357067859) @hrynko - thoughts?

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by hrynko** [comment]
Hi @gkweb,

Thanks for describing your suggestion. This approach is quite similar to what we used in `v1`, which, unfortunately, brought maintenance challenges over time. For now, I’m more inclined to refine `v1` rather than returning to that structure.

I appreciate your input — it’s always helpful to get fresh perspectives!
