### ISSUE TITLE
Sharing source between instances

### ISSUE THREAD

**Issue by EHadoux** [hrynko/vue-pdf-embed#24]
Hello,

first, thanks a lot for the component, it's slick. 
Like the other fella in #9 I come from a library where pages are displayed one by one. So here I've use a `v-for` around the component with the `:page` prop. So far so good. I'm doing that because I need to decorate each page (checkboxes, etc. around every page, not sure I'm doing it the best way possible though).
 
However, because the loading is done inside the component, I have to have another instance, with `v-show="false"` just to be able to get the number of pages to feed to the `v-for` through a ref. Other components load the pdf outside and so we can get the number of pages without ref to the component. But here it needs to be rendered to be ref'd, and so we need to have the number of pages for that, so it needs to be rendered and ref'd, so it's a loop. 
Now my question: is the source shared by all component instances? (I see it's loaded with a worker but I'm not sure of the behaviour). Just to be sure I'm not multiplying the pdf in memory.
Cheers!

**Comment by EHadoux** [comment]
Hey, thanks for you response. 
Here is what I mean:
![image](https://user-images.githubusercontent.com/1655646/165355778-a6eb3ab1-2cae-4dc0-a62a-f2af14ee6b87.png)

As you can see, each page is decorated with checkboxes and a button. It's not just styling but actual elements.
In order to do that, I iterate across all the pages and display them 1 by 1 with the checkboxes.
```vue
<div v-for="i in pages" :key="i">
  <q-checkbox label="Cover" />
  ...
  <vue-pdf-embed :source="src" disableAnnotationLayer disableTextLayer :page="i" />
</div>
```
Problem 1: as you can see, I'm multiplying the instances of the component, one per page.
Problem 2: this `pages` variable can contain a number only once the document has been loaded. But it can be loaded only if we execute the `v-for` which requires `pages` to contain a number (that's a deadlock).
So to solve that, I've put yet another instance at the very top, that loads but is not displayed:
```vue
<vue-pdf-embed :source="src" disableAnnotationLayer disableTextLayer @rendered="loaded" v-show="false" />
```
When that instance emits `rendered`, I can populate `pages` that in turns triggers the `v-for` and displays the individual pages.

So going back to the initial issue and the one in #9.
For problem 1, it's actually not a problem if the underlying resource (the PDF) is loaded only once in memory and shared.
For problem 2, this is due to the fact that the loading of the PDF is done inside the VuePdfEmbed component, and not outside like in, e.g., vue-pdf.

I'm not bothered that much by the workaround, this part is not client-facing, but I was wondering if there is a better way of doing it.

Cheers!

**Comment by hrynko** [comment]
I see the problem, thanks for the details.

Could you address the question about memory usage (if it is loaded once for the same sources) in the PDF.js repo? At first glance it doesn't seem that way, but I can be wrong.

**Comment by EHadoux** [comment]
That's amazing, thanks a lot! I'll check that out soon. Cheers 👍

**Comment by hrynko** [comment]
Changes from @mweimerskirch have been included in `1.1.2`

In this release, a `getDocument` function was also attached to the exported module. So that you can load the PDF document outside the component as follows:

```vue
<template>
  <div>
    <div v-if="pdfSource">
      <vue-pdf-embed :source="pdfSource" :page="1" />
      <vue-pdf-embed :source="pdfSource" :page="3" />
    </div>
  </div>
</template>

<script>
import VuePdfEmbed from 'vue-pdf-embed'

export default {
  components: {
    VuePdfEmbed,
  },
  data() {
    return {
      pdfSource: null,
    }
  },
  async mounted() {
    this.pdfSource = await VuePdfEmbed.getDocument('<PDF_SOURCE>').promise
  },
}
</script>
```

Hope this helps

**Comment by EHadoux** [comment]
We've tested on our end, and we're not exactly sure about this bit:
https://github.com/hrynko/vue-pdf-embed/blob/c1e20be7a2a45e1ccd0dcc0450b4c71ad65eac25/src/vue-pdf-embed.vue#L165

When packed, all the class names are supposed to be minimised, so I don't think `"PDFDocumentProxy"` actually exists. When we run 
```typescript
(await VuePdfEmbed.getDocument('<PDF_SOURCE>').promise).constructor.name
``` 
it gives us `e`, the minimised name, so it seems we never end up in the true side of the if.

**Comment by hrynko** [comment]
@mweimerskirch could you take a look at that?
