### ISSUE TITLE
Feature request: Print method

### ISSUE THREAD

**Issue by zenflow** [hrynko/vue-pdf-embed#27]
`vue-pdf` has a public method to bring up browser's print dialog for the PDF: https://github.com/FranckFreiburger/vue-pdf#public-methods

It can be invoked simply:

```js
methods: {
    print () {
      this.$refs.myPdfComponent.print()
    },
}
```

My team's project needs this feature to move away from `vue-pdf` which lacks support for both (1) Vue3 and (2) ES Modules / Vite.

What do you think @hrynko ? Would you review/accept a PR to implement this?

**Comment by hrynko** [comment]
There is now a `print` method in the version `1.1.2`. It takes an optional print resolution parameter, otherwise it works just as you described.

Thanks for the request!
