### ISSUE TITLE
How to use it for Vue 2?

### ISSUE THREAD

**Issue by thanhhai1999** [hrynko/vue-pdf-embed#3]

**Comment by hrynko** [comment]
Hi @thanhhai1999!

I take it you've already dealt with this issue. But I'll leave a note here for developers who may encounter this problem in the future.

Installation is the same for both Vue 2 and Vue 3 (see [README.md](https://github.com/hrynko/vue-pdf-embed#installation)). You can find 4 files in the `dist` directory of the installed the package:

```shell
dist
┣ vue2-pdf-embed.js          # UMD module for Vue 2
┣ vue2-pdf-embed.worker.js   # Fallback PDF WebWorker
┣ vue3-pdf-embed.js          # UMD module for Vue 3
┗ vue3-pdf-embed.worker.js   # Fallback PDF WebWorker
```

Thus, there are different files builds for Vue 2 and Vue 3. By default, the module is exported as for Vue 3:

```js
import VuePdfEmbed from 'vue-pdf-embed'
```

For Vue 2, you have to explicitly name the build file:

```js
import VuePdfEmbed from 'vue-pdf-embed/dist/vue2-pdf-embed'
```

The name of the build file can also be specified when installing via the CDN (see [unpkg.com](https://unpkg.com)):

```html
<script src="https://unpkg.com/vue-pdf-embed/dist/vue2-pdf-embed.js"></script>
```

**Comment by nowrap** [comment]
In a typescript vue 2 project it's complaining about the missing ts declaration:
`TS7016: Could not find a declaration file for module 'vue-pdf-embed/dist/vue2-pdf-embed'.`

Can the existing index.d.ts file somehow used for vue 2?

**Comment by hrynko** [comment]
UPD: This is no longer needed, since `1.1.3` there are two separate typings (for Vue 2 and Vue 3).
