### ISSUE TITLE
is the original document size data available?

### ISSUE THREAD

**Issue by ekrausso** [hrynko/vue-pdf-embed#34]
Hi.. I need to work with the document's original dimensions.. (A4, A3, ...) is this available in px on vue-pdf-embed? I can't find any reference to this.
thank you!

**Comment by mweimerskirch** [comment]
@ekrausso 
The document doesn't have dimensions, but the pages do. Each page can have different dimensions.

You can use the "loaded" event to get an object representing the PDF document and then iterate through the pages. The PDFPage object has a "getViewport" method (https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib-PDFPageProxy.html). You should be able to deduce the page size from there. 72 units are equal to one inch. So you need to divide the units (width and height) by 72 to get inches and then multiply by 25.4 to get millimeters.

**Comment by ekrausso** [comment]
hi @mweimerskirch  and @hrynko .. sorry if I didnt make myself clear before... yes I want the page dimensions... also thank you! Im trying what you suggested but I think I'm having the same issue as #37 ... trying to log the value of this event but I'm not getting anything

**Comment by hrynko** [comment]
I'm closing the issue since the `loaded` event was included in `1.1.2`. Feel free to reopen it if you need more help.

**Comment by ekrausso** [comment]
thanks! @hrynko

**Comment by hugo-cardoso** [comment]
Is there a possibility to access PageProxy?

**Comment by hrynko** [comment]
A document proxy can be accessed via [template ref](https://vuejs.org/guide/essentials/template-refs.html) (`document` data property) or as a `loaded` event value
