### ISSUE TITLE
Loaded event not exist

### ISSUE THREAD

**Issue by woolimi** [hrynko/vue-pdf-embed#37]
Hello,  @hrynko ! Thanks for making an awsome package 🙏

When I am using your vue-pdf-embed, 
I found that `loaded` event is missing.

Could you please fix it ? thx thx

**Comment by hrynko** [comment]
Hi @woolimi,

The `loaded` event has been added, but not yet included in the release. Thus, it is not available in the npm package. I plan to release a new version soon, but if you need it urgently, you can install the library via GitHub.

**Comment by ekrausso** [comment]
Hi @hrynko .. I will try via Github for now thanks... do you have an estimate for the new release by any chance? so sorry to bother you....!

**Comment by hrynko** [comment]
Hopefully next week.

**Comment by hrynko** [comment]
Hi @woolimi @ekrausso 

The `loaded` event was released in `1.1.2` and is now available in the npm registry
