### ISSUE TITLE
Nuxt3 -  throwing "A plugin must either be a function or an object with an "install" function."

### ISSUE THREAD

**Issue by ChristopherJohnson25** [hrynko/vue-pdf-embed#38]
I'm using Nuxt3 and the addon is giving error, 

` A plugin must either be a function or an object with an "install" function.`

vue-pdf-embed inpackage.json

`"vue-pdf-embed": "^1.1.1"`

Nuxt3 plugin, vue-pdf-embed.client.js:

`import VuePdfEmbed from "vue-pdf-embed";
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(VuePdfEmbed)
});`

Has anyone had any success with Nuxt3?

**Comment by hrynko** [comment]
Hi @ChristopherJohnson25,

There is no `install` function in the library, so you should manually register the component as follows:

```js
nuxtApp.vueApp.use('VuePdfEmbed', VuePdfEmbed)
```

**Comment by ChristopherJohnson25** [comment]
@hrynko - this does not seem to fix the error. I've updated to below and no change.

`import VuePdfEmbed from 'vue-pdf-embed';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use('VuePdfEmbed', VuePdfEmbed)
});`

**Comment by hrynko** [comment]
Is it the same error?

**Comment by ChristopherJohnson25** [comment]
@hrynko  - yes same error.

**Comment by hrynko** [comment]
Sorry, my bad. Not `use`, but `component`:

```js
nuxtApp.vueApp.component('VuePdfEmbed', VuePdfEmbed)
```

**Comment by ChristopherJohnson25** [comment]
Ok - new errrors! Progress, thank you. I will debug - anything else is likely something on my end.

**Comment by hrynko** [comment]
Excellent. You can look for clues in issues #12 and #21.

PS: Please post your solution if it can be useful to other developers.
