### ISSUE TITLE
How to clean the PDF?

### ISSUE THREAD

**Issue by IsraelSistemas** [hrynko/vue-pdf-embed#44]
There's a way to clean the PDF?, for example, I select a PDF and is shown in the component, everything is fine, but when I try to delete the selected pdf, is not cleaned from the component; there's a solution for that?

**Comment by hrynko** [comment]
In general, a component can only be rendered if the `source` prop is provided. If this prop is missing, an error will occur. So in your case, I recommend conditionally displaying the component until the document is "deleted".
