### ISSUE TITLE
suggestion - add file name parameter () to print() function

### ISSUE THREAD

**Issue by KC900201** [hrynko/vue-pdf-embed#45]
Hi @hrynko ,

I've come across your work vue-pdf-embed and I have a question about the built-in print() function from the library. I use your package to enable file preview of pdf on my work. While I attempt to save the pdf file from the Chrome browser prompt-in print window (I choose 'Save As Pdf' instead of 'Print' as my option), I found that the name of the file about to be saved is different from the original file name. The file name appears to be the name of the website I'm working on.

![image](https://user-images.githubusercontent.com/46585072/172770692-163f7919-633f-4131-b7a1-99d47c3d81b8.png)
Image 1: the original file name as shown

![image](https://user-images.githubusercontent.com/46585072/172770819-ce81888c-b629-40b7-bb59-6b00a83f5321.png)
Image 2: Attempting to save the preview pdf

![image](https://user-images.githubusercontent.com/46585072/172770885-9355108b-dd77-40d7-b698-bc5c8cd2438c.png)
Image 3: Prompt window showing a different file name that is not the same as the original one.

Is there a workaround to include a 'file_name' parameter besides than **number** to indicate the dpi for the printing, or we can default set the file name to be same as the original file when we are using the print() function?

**Comment by KC900201** [comment]
Hi @hrynko , any updates on this ticket?

**Comment by hrynko** [comment]
Hi @KC900201,

Unfortunately, it is not possible to get the original name of the PDF due to internal restrictions. But I can add the suggested `filename` argument to the `print` method, so that to pre-define the name of the file to be saved. I will include this in the next release and let you know when it is available.

**Comment by KC900201** [comment]
@hrynko thanks for your prompt response. Okay, will wait for your updates

**Comment by hrynko** [comment]
UPD: This was released in `1.1.3`
