### ISSUE TITLE
Reference error when attempting to rotate pdf

### ISSUE THREAD

**Issue by KC900201** [hrynko/vue-pdf-embed#49]
Encountered error below when attempting to update the value of **rotation** in vue-pdf-embed

Currently using vuejs version 2.* for the project

![image](https://user-images.githubusercontent.com/46585072/174015111-958f5d12-d6f9-4229-9dfe-113635c76ddf.png)

Below are the code snippets:

![image](https://user-images.githubusercontent.com/46585072/174015478-12a39ce9-7e73-4936-90be-fd5747ae0f37.png)
vue-pdf-embed

javascript function to tweak the value

![image](https://user-images.githubusercontent.com/46585072/174015642-cb094f23-94ce-4de7-a1f3-1c6fb8faf8ca.png)

**Comment by hrynko** [comment]
Hi @KC900201,

At first glance, it looks like a typo `this -> his`, but it is not clear where it happened. Could you maybe prepare a sample project in JSFiddle/CodeSandbox/etc to demonstrate this issue?

**Comment by KC900201** [comment]
Hi @hrynko,

It could be a glitch when handling the function, as the error occurs spontaneously. Anyhow, I will try to update in this thread and provide the code snippet possibly. For now, I will close this thread.

**Comment by KC900201** [comment]
@hrynko Found the Unreferenced error is due to wrong labelling of my coding. So, I will close this tix permanently
