### ISSUE TITLE
Vue3: Importing vue-pdf-embed makes all jest unit tests fail

### ISSUE THREAD

**Issue by sbourouis** [hrynko/vue-pdf-embed#5]
Hi,

I'm currently using `vue-pdf-embed: ^1.0.5` and my unit tests are all failing. I have this error:

```bash
    Inline worker is not supported

       6 |
       7 | <script lang="ts">
    >  8 | import VuePdfEmbed from 'vue-pdf-embed';
         | ^
       9 | import { Vue, Options } from 'vue-class-component';
      10 |
      11 | @Options({

      at e.exports (node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:377673)
      at new <anonymous> (node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:379452)
      at node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:379427
      at node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:1229100
      at node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:1229124
      at node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:170
      at Object.<anonymous> (node_modules/vue-pdf-embed/dist/vue3-pdf-embed.js:1:340)
      at Object.<anonymous> (src/components/PdfViewer.vue:8:1)
      at Object.<anonymous> (src/App.vue:10:1)
      at Object.<anonymous> (tests/unit/example.spec.ts:2:1)
```

Any idea about what could cause this? I've made a small repro here https://github.com/sbourouis/vue-pdf-embed-bug-repro
When we run `yarn test:unit` the test fail and we have the error shown above. (See result [here](https://github.com/sbourouis/vue-pdf-embed-bug-repro/runs/4756272480?check_suite_focus=true))

**Comment by sbourouis** [comment]
I've fixed it by mocking `vue-pdf-embed` with jest by mocking it globally
See https://github.com/sbourouis/vue-pdf-embed-bug-repro/commit/2474ee0c6e5f187b3bc13b97079f0d118f7e79be
Tests results https://github.com/sbourouis/vue-pdf-embed-bug-repro/runs/4756292365?check_suite_focus=true

**Comment by damiensauvalle** [comment]
thanks !
