### ISSUE TITLE
Error just instaling in nuxt2 project

### ISSUE THREAD

**Issue by fabiovaz** [hrynko/vue-pdf-embed#51]
ERROR  Failed to compile with 1 errors                                                                                               friendly-errors 17:19:28  
 ERROR  in ./node_modules/vue-pdf-embed/dist/vue2-pdf-embed.js                                                                        friendly-errors 17:19:28  

Module parse failed: Unexpected token (1:529323)                                                                                      friendly-errors 17:19:28  
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by hanns2002** [comment]
me too, with vue3-pdf-embed.js same error on version 1.1.3

**Comment by hrynko** [comment]
Hi @fabiovaz @hanns2002,

There was a transpiling issue in `1.1.3`. It is now fixed in `1.1.4`.

Thanks for noticing!
