### ISSUE TITLE
Props `scale` not working 

### ISSUE THREAD

**Issue by DescLee** [hrynko/vue-pdf-embed#58]
Props `scale` not working in latest version 1.1.4, may be  it is not published yet?

**Comment by DescLee** [comment]
已收到您的邮件，会尽快进行处理

**Comment by bogdan12893** [comment]
@hrynko Can you help me with the scale prop. I cant figure out how to work with it. I tried setting it to `:scale="20"` for example. This is supose to zome in/out, right?

**Comment by DescLee** [comment]
已收到您的邮件，会尽快进行处理

**Comment by hrynko** [comment]
> This is supose to zome in/out, right?

Not really, it represents the ratio of canvas size to document size. So it is more about optimization, you can adjust it based on your canvas size if you need to optimize the memory usage (the larger `scale` value, the better image quality, the more memory usage).

This prop has an automatic value, so you don't have to use this prop unnecessarily. And to implement scaling, I would suggest considering the `width` prop and constraining the component in a scrollable parent block.

**Comment by nullhan** [comment]
> > This is supose to zome in/out, right?
> 
> Not really, it represents the ratio of canvas size to document size. So it is more about optimization, you can adjust it based on your canvas size if you need to optimize the memory usage (the larger `scale` value, the better image quality, the more memory usage).
> 
> This prop has an automatic value, so you don't have to use this prop unnecessarily. And to implement scaling, I would suggest considering the `width` prop and constraining the component in a scrollable parent block.

So what you mean is to change the width of the parent element of the canvas to implement the scaling function, for example using transform:translateZ(0) scale(10)

**Comment by DescLee** [comment]
已收到您的邮件，会尽快进行处理

**Comment by TLovers** [comment]
em~~~~~ scale not working

**Comment by Krue1** [comment]
same here

**Comment by DescLee** [comment]
已收到您的邮件，会尽快进行处理

**Comment by hrynko** [comment]
It's been a while, but `scale` prop is now included in `1.1.5`. Sorry for delay.

**Comment by DescLee** [comment]
已收到您的邮件，会尽快进行处理
