### ISSUE TITLE
Expose a function to cancel rendering job in worker

### ISSUE THREAD

**Issue by fabiiomiiguel** [hrynko/vue-pdf-embed#59]
Hello, first of all thank you for your amazing package.

My feature request is because, I use a modal with your pdf viewer, and some times if we are too quickly the worker doesn't stop is previous rendering  job.
So if we close while its still rendering and re-open immediately after. The package will throw an error and then we need to close and re-open again to make it work.

So maybe it would be nice to have some type of function to call with `this.$refs`, to cancel the current job rendering manually.

**Comment by hrynko** [comment]
Hi @fabiiomiiguel,

According to the description it looks very similar to [this one](https://github.com/hrynko/vue-pdf-embed/issues/40#issuecomment-1171107732). This has already been fixed but not released.

**Comment by fabiiomiiguel** [comment]
Yes maybe it's related, when you release that version, I would let you know if that solves my question.

**Comment by hrynko** [comment]
It's been a while, but it's released in `1.1.5`

Feel free to reopen this issue if it's not fixed
