### ISSUE TITLE
Digital signatures are not rendered

### ISSUE THREAD

**Issue by hgoncalves** [hrynko/vue-pdf-embed#6]
First of all I would like to thank you for the work done with this component which makes life much easier for displaying pdfs with Vue. 

Unfortunately in my use (Vue 2 version) I noticed that it does not display the rendering of digital signatures. 

Unless I'm mistaken pdfjs allows it, [pdfjs-vue](https://github.com/Funny002/pdfjs-vue) this component for example does, do you think it would be possible to add this?

Thanks in advance ;)

**Comment by hrynko** [comment]
Hi @hgoncalves,

Thank you for discovering this. I'll look into it and get back to you with a solution.

**Comment by hgoncalves** [comment]
Hi @hrynko, thanks, I appreciate ;)

**Comment by hrynko** [comment]
I just published `1.0.6`, which now has support for digital signatures. Feel free to reopen this issue if it is not fixed.
