### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by AndrewStoddard** [hrynko/vue-pdf-embed#60]
I am trying to use this to view pdfs in an IE 11 environment, however, I am receiving a SCRIPT 1002 error. When I follow the link to the chunk venders, this is the code that seems to be causing the issue.

![image](https://user-images.githubusercontent.com/49331341/178776829-2f1575c8-706c-4f78-9b3e-005befba70ec.png)

I believe the issue to be the lambda function not transpiling to ES5, but have no clue why. 

Here are the relevant files: 

babelrc
`{
    "presets": [
        [
            "@babel/preset-env"
        ]
    ],
    "plugins": [
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-transform-arrow-functions",
        "@babel/transform-runtime"
    ]
}`

babel.config.js
`module.exports = {
    presets: [
        ['@vue/cli-plugin-babel/preset', {
            polyfills: [
                'es.map',
                'es.promise',
                'es.object.assign',
            ],
            useBuiltIns: "entry",
            corejs: 3,
            ignore: /node_modules\/(?!debug)/
        }
    ]],
    plugins: [
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-transform-arrow-functions",
        "@babel/transform-runtime"
    ],
}
`

browserslistrc
`> 1%
last 2 versions
ie 10`

vue.config.js
`module.exports = {
  "productionSourceMap": true,
  "transpileDependencies": [
    "vuetify",
    "debug",
    "vue-pdf-embed"
  ],
  configureWebpack: {
    devtool: 'nosources-source-map'
  },
}`

webpack.config.js
`const webpack = require('webpack');
module.exports = 
  {
    output: {
      clean: true,
      filename: 'edocss-wp.js',
    },
    plugins:[
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('production')
      })
    ]
  };`

**Comment by hrynko** [comment]
Hi @AndrewStoddard,

I doubt I can help fix your build, since I don't know your environment. Also, I assume that this problem is not related to the library. Please reopen the ticket if this is the case.
