### ISSUE TITLE
Import in browser Vue 3 version

### ISSUE THREAD

**Issue by lianee** [hrynko/vue-pdf-embed#62]
Using `<script src="https://unpkg.com/vue-pdf-embed"></script>` to load the script for vue 3 in browser gives the following error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'createVNode')`

Could you please update the jsfiddle examples to work with Vue 3?

update: checking with various versions, the last one working seems to be 1.0.8

**Comment by micro-bean** [comment]
![image](https://user-images.githubusercontent.com/29078931/228113343-32dd4597-1e0c-43cf-bdca-66d80cee01f5.png)
e.VuePdfEmbed=t(e.Vue)

**Comment by hrynko** [comment]
Hi @micro-bean, do you have any ideas/Insights?

**Comment by micro-bean** [comment]
> Hi @micro-bean, do you have any ideas/Insights?
try:
webpack.config.js
`
externals: {
    vue: 'Vue',
},
`

**Comment by hrynko** [comment]
This is already there, please check [webpack.config.js](https://github.com/hrynko/vue-pdf-embed/blob/master/webpack.config.js)

**Comment by hrynko** [comment]
This has been resolved in `v2.0.0` after switching to Vite
