### ISSUE TITLE
How to render the waterMark?

### ISSUE THREAD

**Issue by chenbin134** [hrynko/vue-pdf-embed#63]
thanks for your plugin.
i have a question,
my PDF has some waterMark,but can't be rendered.
What should I do?

**Comment by hrynko** [comment]
Hi @chenbin134,

I checked several watermarked PDFs but wasn't able to reproduce. Would you be able to prepare an example that reproduces the issue?

**Comment by chenbin134** [comment]
@hrynko Hi,On that question,you use this PDF file : https://ts.midbj.com/evidence_integration/Fulltext-sample.pdf
that will reproduces the issue
![截屏2022-07-28 下午2 36 44](https://user-images.githubusercontent.com/41474653/181437482-ec2cfc46-19da-4ab5-baff-d9fa818721a3.png)

**Comment by hrynko** [comment]
It's been a while, but please check #80

It's not a watermark issue, but a font issue
