### ISSUE TITLE
Method `print` send only current page to print 

### ISSUE THREAD

**Issue by nickxgrom** [hrynko/vue-pdf-embed#67]
Hi, @hrynko 
If we're in pagination-mode, like `<vue-pdf-embed :page="page"` and call `print` method, then it will printed only current page
Is there is way to print whole pdf, even we're looking one page?

**Comment by hrynko** [comment]
Hi @nickxgrom,

As a workaround, you can render an "invisible" component in the meantime without a `page` prop. Also, I will consider updating the `print` method for this case. Thanks!

**Comment by hrynko** [comment]
I updated the `print` method signature so that `page` prop can now be overridden (see 9eaa57a)

Will include this in the next release if it works for you
