### ISSUE TITLE
I want to add a loaded animation when using link loading

### ISSUE THREAD

**Issue by hongjunlong** [hrynko/vue-pdf-embed#70]
I want to add a loaded animation when using link loading

**Comment by tomhoma** [comment]
you can use component from ui framework like this 
[https://www.antdv.com/components/spin](url)

**Comment by hongjunlong** [comment]
However, Vue PDF is responsible for loading files when using links. I cannot add spin at the beginning and end

**Comment by hongjunlong** [comment]
I am now requesting Base64 and adding animation

**Comment by hrynko** [comment]
Thanks for the suggestion @tomhoma!

However, I would suggest to convert this issue to [discussion](https://github.com/hrynko/vue-pdf-embed/discussions), as it doesn't refer directly to the library, but rather to its application.

It also depends on whether you are displaying all pages at once or page by page. Please provide more details when opening a discussion. Thanks!
