### ISSUE TITLE
Checkbox no longuer display as checked

### ISSUE THREAD

**Issue by jacquesmi** [hrynko/vue-pdf-embed#8]
When displaying a pdf with checkboxes, checked one no longuer display as checked in version 1.0.6.
It was working fine in version 1.0.5.

Steps to reproduce:
1 - Goto this sample vue-pdf-embed : https://jsfiddle.net/n6oa59bu/

2 - Replace version 1.0.5 to 1.0.6 in the script reference, the checkbox "Reading" is no longuer checked in version 1.0.6.

**Comment by hrynko** [comment]
Hi @jacquesmi,

Thank you for discovering this. I'll try to fix it.

**Comment by jacquesmi** [comment]
Not sure but it may be related to this commit :
https://github.com/hrynko/vue-pdf-embed/commit/2ebeb3e522ea9d05e81aee5ff1288230e40d82b5

**Comment by hrynko** [comment]
Yes, it's definitely related.

In this commit `PDF.js` was updated to `2.10.377` (to support digital signatures, #6). I tried downgrading `PDF.js` to `2.9.359` and that seems to fix the checkbox issue, keeping support for digital signatures. I'll look into the issue some more, but this might be the solution.
