### ISSUE TITLE
Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.

### ISSUE THREAD

**Issue by satcon** [hrynko/vue-pdf-embed#80]
Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.

**Comment by zhangxiang0316** [comment]
// pdfSource: '../src/2.pdf', 
pdfSource: {
        url: '../src/2.pdf',
        cMapUrl: 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.16.105/cmaps/',
        cMapPacked: true,
      },

**Comment by hrynko** [comment]
Thanks @zhangxiang0316! It seems to be the answer 👍
