### ISSUE TITLE
HMR support broken

### ISSUE THREAD

**Issue by FossPrime** [hrynko/vue-pdf-embed#82]
For some reason every time the parent component is HMR updated, vue-pdf-embed refuses to load the document. As if it has a memory that it already loaded it, but hasn't actually.

To reproduce just make a one line script change, white space works. Vite will then HMR your component and the pdf will not load, despite having a valid URL.

My workaround is to use an objectUrl as source...

```
const fetchRes = await fetch(this.source)
const pdfBlob = await fetchRes.blob()
this.pdfObjectUrl = window.URL.createObjectURL(pdfBlob) // src
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/876076/187007021-1ce8eecd-8111-4f06-8414-f0e6e3216b31.png">

[Reproduction](https://stackblitz.com/edit/vue-pdf-embed?file=README.md,src%2FApp.vue)

**Comment by hrynko** [comment]
Hi @FossPrime,

Sorry, it's not clear from the description what exactly is wrong. Could you please rephrase it?

**Comment by FossPrime** [comment]
> Hi @FossPrime,
> 
> Sorry, it's not clear from the description what exactly is wrong. Could you please rephrase it?

It's harder to develop because any hot module reloading events break the component. This only affects the developer experience, not the end user running `vite build` output.

**Comment by hrynko** [comment]
I couldn't reproduce it in the Stackblitz project you provided (nothing breaks on changes)

**Comment by hrynko** [comment]
This should be resolved after several memory usage optimizations and switching to Vite

Please try `v2.0.0` and reopen the issue if needed
