### ISSUE TITLE
Possibility of adding Slots.

### ISSUE THREAD

**Issue by dougieled** [hrynko/vue-pdf-embed#84]
Wondering is it possible to add slots into the vue-pdf-embed.vue. I still need to test out which would be best but possibly an option of having a slot inside and outside of the v-for. 

Currently using a wrapper over the top of the vue-pdf-embed which highlights text based on the position of text using textract positioning geometry. However only one page will work at a time. Would possibly be more straight forward to use a slot in order to import my component to sit on top of each page and i can pass each texttract options based on each page

**Comment by noah1234j** [comment]
Hi dougieled, 

Could you possibly share your code on how you are tackling this? I have a use case and am curious.

**Comment by hrynko** [comment]
Hi @dougieled,

There is no slots available right now, could you describe the possible use cases for them?

**Comment by hrynko** [comment]
Slots were added in #157 and are available in `v1.2.0`
