### ISSUE TITLE
Vue-pdf parity?

### ISSUE THREAD

**Issue by p3v9d5ui** [hrynko/vue-pdf-embed#9]
Hi,

First off, I'm really glad to see a new Vue component for PDF rendering :-)

I'd like to migrate to this from vue-pdf, but vue-pdf-embed is missing a couple of features I rely on. For my application, I render each PDF page separately (i.e., I iterate through the pages and would have a separate <vue-pdf-embed> for each. For this to work, I need an event which gives me the total pages in the PDF. The vue-pdf package provides @num-pages for this. Is there a way to get this info from vue-pdf-embed?

Secondly, to navigate to the correct page, I use vue-pdf's @link-clicked event to get the page number. Is this possible with vue-pdf-embed?

Thanks!

**Comment by hrynko** [comment]
Hi @p3v9d5ui,

Thank you! I hope that the experience of using `vue-pdf-embed` will not disappoint you.

In `vue-pdf` the `page` property is set to `1` by default, which is pretty weird for me. In contrast, `vue-pdf-embed` renders the entire document if the page property is not explicitly specified. So you don't have to iterate through the document manually. However, if needed, you can still access the number of pages in the document via template ref ([see example](https://jsfiddle.net/hrynko/we7p5uq4)).

As for working with links, this is not yet available, as well as the text layer itself. I plan to add this over time, however a pull request for this is welcome.

**Comment by p3v9d5ui** [comment]
Hi @hrynko ,

Thank you! I've tested this and it works fine. 

I've submitted a small PR: https://github.com/hrynko/vue-pdf-embed/pull/11. This just adds the ability to supply a Uint8Array to the source property. It's just a matter of declaring that type, because otherwise it works fine. Are you able to merge it?
