### ISSUE TITLE
 Bug/Security: usage of 'eval' function is blocks pdf rendering when CSP is enabled

### ISSUE THREAD

**Issue by Diana5** [hrynko/vue-pdf-embed#90]
PDF cannot be previewed due to the usage of `eval` function when enabling Content Security Policy with script-src 'self'.
In order to overcome this issue `unsafe-eval` has to be added, but this would only increase security vulnerabilities.

vue-pdf-embed - 1.1.2
vue - 3.2.31
Browser - Firefox/Chrome

**Comment by simonmaass** [comment]
can confirm!

**Comment by hrynko** [comment]
Hi @Diana5,

The `eval` function is used for the worker loading. I'm not sure if there are other options to load it, but I'll check.

**Comment by jbbergy** [comment]
hi,

Any news about this issue ? we meet the same in our project.

**Comment by hrynko** [comment]
No easy solution so far, but I'm planning to add more builds in the next minor release, so that the lib can be imported without the worker

**Comment by jbbergy** [comment]
thanks for the answer.

We previously used the lib pdfvuer and we had no issue like that (but it has other issue). it use worker's too, but the way is it loaded is different. Maybe it's an idea.

**Comment by markus-ebner** [comment]
Any news on this issue?

**Comment by hrynko** [comment]
In `v2.0.0` there is an additional build (`index.essential.mjs`) exported which doesn't load the worker, but exposes `GlobalWorkerOptions` instead. Hopefully, using it along with the worker loaded from PDF.js would be a solution.

Please check a [note](https://github.com/hrynko/vue-pdf-embed/tree/v2.0.0#web-worker-loading) about it in README
