### ISSUE TITLE
Scale Props is not working

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [hrynko/vue-pdf-embed#93]

**Comment by AmmarMohamadIsmaeel** [comment]
Using The Scale Props is making the PDF Blurry

**Comment by chao-lyu** [comment]
same problem with `scale` props

**Comment by hrynko** [comment]
Hi @AmmarMohamadIsmaeel,

The `scale` prop represents the desired ratio of canvas size to PDF document size. It is set optimal by default, but can be changed it to suit your needs. The ratio should be re-evaluated if the document becomes blurry.
