### ISSUE TITLE
Add Authorization headers to URL-based pdf fetching

### ISSUE THREAD

**Issue by samul-1** [hrynko/vue-pdf-embed#95]
Great package!

I know vue-pdf-embed supports password-based authentication to access pdf's from a url, but I there's no way to provide token-based authorization.

I see that internally you call pdfjs' `getDocument` function, which does accept custom headers: https://github.com/mozilla/pdf.js/issues/3852#issuecomment-373169304

Is there any chance a prop could be added to vue-pdf-embed to pass custom headers, so that urls that require token authorization can be accessed to fetch pdf's?

**Comment by hrynko** [comment]
Hi @samul-1,

Since the `source` prop can be an object and is passed directly to the `getDocument` function, you can pass the `DocumentInitParameters` as follows:

```vue
<template>
  <vue-pdf-embed
    :source="{
      url: FOO,
      httpHeaders: BAR,
      withCredentials: true,
    }"
  />
</template>
```

**Comment by Vishal-Sharma-rhythm** [comment]
Thanks, It's working for me.
